### ISSUE TITLE
Breaks on empty comments

### ISSUE THREAD

**Issue by crow1170** [PhantomInsights/comments-generator#1]
It's possible to have a zero-length body for a comment by commenting non-printing chars. This breaks step2.py line 42.

**Comment by agentphantom** [comment]
Thank you for this report, I need to reproduce it, in order to be able to fix it.

Do you know a reddit username that I can use to debug this?

**Comment by crow1170** [comment]
Crow1170

**Comment by crow1170** [comment]
More specifically, https://www.reddit.com/r/FanTheories/comments/3bt3m4/walking_dead_why_the_show_may_be_more_clever_than/csq7r4j

**Comment by agentphantom** [comment]
Thank you, I have fixed it in the latest commit.
